local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fi', builtin.git_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('v', '<leader>fq', function()
  local save = vim.fn.getreg('z')
  local savetype = vim.fn.getregtype('z')
  vim.cmd('normal! "zy')
  local text = vim.fn.getreg('z'):gsub('%s+', ' '):gsub('^%s+', ''):gsub('%s+$', '')
  vim.fn.setreg('z', save, savetype)
  vim.cmd(string.format("exec 'Telescope grep_string default_text=' . escape(%s, ' ')", vim.inspect(text)))
end)
require('telescope').load_extension('fzf')
require("telescope").load_extension('harpoon')
