import = ["./rose-pine.toml"]

[font]
size = 13


[font.normal]
family = "BlexMono Nerd Font Mono Medium"

[window.padding]
x = 10
y = 10

[window]
opacity = 0.7
#background_opacity = 0.7
startup_mode = "Maximized"

